config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "people#index"
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id          :integer          not null, primary key
#  first_name  :string
#  last_name   :string
#  middle_name :string
#  sex         :string
#  full_name   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Person < ApplicationRecord
  validates :first_name, presence: true
  validates :sex, inclusion: { in: %w(male female) }
  has_many :declensions, class_name: 'PersonDeclension', dependent: :destroy

  after_initialize :set_full_name
  after_save :set_declensions

  DECLENSIONS = %w(genitive dative accusative instrumental prepositional).freeze

  def set_full_name
    self.full_name = [first_name, middle_name, last_name].join(" ").gsub(/\s+/, ' ')
  end

  def set_petrovich
    Petrovich(
        lastname: last_name,
        firstname: first_name,
        middlename: middle_name,
        gender: sex.to_sym
    )
  end

  def set_declensions
    person = set_petrovich
    DECLENSIONS.each do |decl|
      declension = {
          case: decl,
          first_name: person.to(decl.to_sym).firstname,
          last_name: person.to(decl.to_sym).lastname,
          middle_name: person.to(decl.to_sym).middlename,
          full_name: person.to(decl.to_sym).to_s
      }
      if current_decl = declensions.find_by(case: decl)
        current_decl.update(declension)
      else
        declensions.create(declension)
      end
    end
  end

  def full_genitive
    declensions.find_by(case: 'genitive').full_name
  end
end

app/models/person_declension.rb
# == Schema Information
#
# Table name: person_declensions
#
#  id          :integer          not null, primary key
#  person_id   :integer
#  case        :string
#  first_name  :string
#  middle_name :string
#  last_name   :string
#  full_name   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class PersonDeclension < ApplicationRecord
  belongs_to :person
  validates :case, inclusion: { in: Person::DECLENSIONS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person
    else
      flash[:error] = @person.errors
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to @person
    else
      flash[:error] = @person.errors
      render :edit
    end
  end

  def destroy
    if @person.destroy
      flash[:notice] = 'Person successfully destroyed'
    else
      flash[:error] = 'Something went wrong, please, try again.'
    end
    redirect_to people_path
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :middle_name, :sex)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProcessOptima</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.slim
= bootstrap_form_for @person do |form|
  = form.text_field :first_name, label: 'Имя'
  = form.text_field :last_name, label: 'Фамилия'
  = form.text_field :middle_name, label: 'Отчество'
  = form.select :sex, options_for_select([%w(Мужской male), %w(Женский female)]), label: 'Пол'
  = form.submit 'Отправить'

app/views/people/edit.html.slim
.container
  .row
    .col-sm-12
      h2.page-title Редактировать человека
      = render 'people/form'
      br
      p = link_to 'Перейти на страницу персоны', person_path(@person)
      p = link_to 'Вернуться к списку', people_path

app/views/people/index.html.slim
.container
  .row
    .col-sm-12
      h2.page-title Список людей
      table.table
        tr
          td Имя
          td Фамилия
          td Отчество
          td ФИО в род. падеже
          td Пол
          td Действия
          - @people.each do |person|
            tr
              td = person.first_name
              td = person.last_name
              td = person.middle_name
              td = person.full_genitive
              td = t "sex.#{person.sex}"
              td
                = link_to '', person, method: :get, class: 'fa fa-eye'
                = link_to '', edit_person_path(person), class: 'fa fa-edit'
                = link_to '', person, method: :delete, class: 'fa fa-trash'

      p = link_to 'Создать нового человека', new_person_path

app/views/people/new.html.slim
.container
  .row
    .col-sm-12
      h2.page-title Добавить человека
      = render 'people/form'
      p = link_to 'Вернуться к списку', people_path

app/views/people/show.html.slim
.container
  .row
    .col-sm-12
      h2.page-title Персональная страница
      p = @person.full_name

      table.table
        tr
          td Именительный
          td Родительный
          td Дательный
          td Винительный
          td Творительный
          td Предложный
        tr
          td = @person.first_name
          - @person.declensions.each do |decl|
            td = decl.first_name
        tr
          td = @person.middle_name
          - @person.declensions.each do |decl|
            td = decl.middle_name
        tr
          td = @person.last_name
          - @person.declensions.each do |decl|
            td = decl.last_name
      br
      p = link_to 'Редактировать персону', edit_person_path
      p = link_to 'Вернуться к списку', people_path